version: '3.4'

services:
  manager:
    image: emqx/edge-manager:1.1.1
    container_name: edge-manager
    ports:
      - "9082:9082"
  kuiper:
    image: emqx/kuiper:1.2.0-slim
    ports:
      - "127.0.0.1:9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: manager-kuiper
    hostname: manager-kuiper
    environment:
      KUIPER__BASIC__DEBUG: "true"
      KUIPER__BASIC__PLUGINHOSTS: "http://52.53.170.189"
      MQTT_SOURCE__DEFAULT__SERVERS: "[tcp://manager-edge:1883]"
  edge:
    image: emqx/emqx-edge:latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:18083:18083"
    container_name: manager-edge
    hostname: manager-edge
  neuron:
    image: emqx/neuron:1.2.0
    ports:
      - "127.0.0.1:7681:7681"
      - "127.0.0.1:1947:1947"
      - "127.0.0.1:7000:7000"
    container_name: manager-neuron
    hostname: manager-neuron
  taos:
    image: tdengine/tdengine:2.0.3.1
    ports:
      - "6030:6030"
      - "6035:6035"
      - "6041:6041"
      - "6030-6040:6030-6040/udp"
    container_name: manager-taos
    hostname: taos
    volumes:
      - taos-grafana-plugin:/root/TDengine-server/connector/grafanaplugin
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: manager-grafana
    hostname: manager-grafana
    volumes:
      - taos-grafana-plugin:/var/lib/grafana/plugins/taosplugin
    depends_on:
      - taos

volumes:
  taos-grafana-plugin: