version: '3.4'

services:
  kuiper:
    image: emqx/kuiper:1.1.0-slim
    ports:
      - "127.0.0.1:9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: demo-kuiper
    hostname: demo-kuiper
    environment:
      MQTT_SOURCE__DEFAULT__SERVERS: "[tcp://demo-edge:1883]"
  edge:
    image: emqx/emqx-edge:latest
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:18083:18083"
    container_name: demo-edge
    hostname: demo-edge
  neuron:
    image: emqx/neuron:1.1.3
    ports:
      - "127.0.0.1:7681:7681"
      - "127.0.0.1:1947:1947"
      - "127.0.0.1:7000:7000"
    container_name: demo-neuron
    hostname: demo-neuron
  agent:
    image: emqx/agent:1.1.0
    container_name: demo-agent
    hostname: demo-agent
    volumes:
      - ./etc:/wormhole/etc